# Generated by Django 5.0.4 on 2024-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='torrents')),
                ('category', models.CharField(choices=[('', 'ANIME'), ('', 'DRAMA'), ('', 'ANIMATION'), ('', 'ACTION')], max_length=2)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('CS', 'CASTELLANO'), ('FR', 'FRENCH')], max_length=2)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
